from sqlalchemy import Column, Integer, String, DateTime, Float, SmallInteger
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()

class Estimate(Base):
    __tablename__ = 'TD見積'

    estimate_number = Column('見積番号', Integer, primary_key=True)
    estimate_date = Column('見積日付', DateTime)
    staff_code = Column('担当者CD', SmallInteger, nullable=False)
    estimate_title = Column('見積件名', String(60), nullable=False)
    customer_code = Column('得意先CD', String(4), nullable=False)
    customer_name1 = Column('得意先名1', String(28), nullable=False)
    customer_name2 = Column('得意先名2', String(28), nullable=False)
    customer_tel = Column('得TEL', String(15), nullable=False)
    customer_fax = Column('得FAX', String(15), nullable=False)
    customer_contact = Column('得意先担当者', String(40), nullable=False, default='')
    delivery_customer_code = Column('納入得意先CD', String(4))
    delivery_code = Column('納入先CD', String(4))
    delivery_name1 = Column('納入先名1', String(28), nullable=False, default='')
    delivery_name2 = Column('納入先名2', String(28), nullable=False, default='')
    postal_code = Column('郵便番号', String(8), nullable=False, default='')
    address1 = Column('住所1', String(32), nullable=False, default='')
    address2 = Column('住所2', String(32), nullable=False, default='')
    delivery_tel = Column('納TEL', String(15), nullable=False, default='')
    delivery_fax = Column('納FAX', String(15), nullable=False, default='')
    delivery_contact = Column('納入先担当者', String(40), nullable=False, default='')
    delivery_start_date = Column('納期S', DateTime)
    delivery_end_date = Column('納期E', DateTime)
    remarks = Column('備考', String(60), nullable=False)
    project_scale_amount = Column('物件規模金額', Float, nullable=False, default=0)
    open_date = Column('オープン日', DateTime)
    project_type = Column('物件種別', SmallInteger, nullable=False)
    site_name = Column('現場名', String(60), nullable=False, default='')
    payment_terms = Column('支払条件', SmallInteger, nullable=False, default=0)
    payment_terms_other = Column('支払条件その他', String(30), nullable=False, default='')
    delivery_display = Column('納期表示', SmallInteger, nullable=False, default=0)
    delivery_other = Column('納期その他', String(30), nullable=False, default='')
    estimate_date_output = Column('見積日出力', SmallInteger, nullable=False, default=0)
    validity_period = Column('有効期限', SmallInteger, nullable=False)
    order_category = Column('受注区分', SmallInteger, nullable=False, default=0)
    order_date = Column('受注日付', DateTime)
    large_small_category = Column('大小口区分', SmallInteger, nullable=False, default=0)
    courtesy_discount = Column('出精値引', Float, nullable=False, default=0)
    total_amount = Column('合計金額', Float, nullable=False, default=0)
    total_cost = Column('原価合計', Float, nullable=False, default=0)
    cost_rate = Column('原価率', Float, nullable=False, default=0)
    external_tax = Column('外税額', Float, nullable=False, default=0)
    tax_aggregation_category = Column('税集計区分', SmallInteger, nullable=False, default=0)
    sales_fraction = Column('売上端数', SmallInteger, nullable=False, default=0)
    consumption_tax_fraction = Column('消費税端数', SmallInteger, nullable=False, default=0)
    estimate_output_date = Column('見積書出力日', DateTime)
    order_issue_date = Column('注文発行日', DateTime)
    purchase_date = Column('仕入日付', DateTime)
    sales_date = Column('売上日付', DateTime)
    customer_specific_estimate_number = Column('得意先別見積番号', Integer, nullable=False, default=0)
    initial_registration_date = Column('初期登録日', DateTime, nullable=False, default=datetime.now)
    registration_change_date = Column('登録変更日', DateTime, nullable=False, default=datetime.now)
    estimate_category = Column('見積区分', SmallInteger, nullable=False, default=0)
    sales_delivery_date = Column('売上納期', DateTime)
    department_code = Column('部署CD', SmallInteger, nullable=False, default=0)
    sales_customer_code = Column('販売先得意先CD', String(4), nullable=False, default='')
    sales_customer_name1 = Column('販売先得意先名1', String(28), nullable=False, default='')
    sales_customer_name2 = Column('販売先得意先名2', String(28), nullable=False, default='')
    sales_delivery_customer_code = Column('販売先納得意先CD', String(4), nullable=False, default='')
    sales_delivery_code = Column('販売先納入先CD', String(4), nullable=False, default='')
    sales_delivery_name1 = Column('販売先納入先名1', String(28), nullable=False, default='')
    sales_delivery_name2 = Column('販売先納入先名2', String(28), nullable=False, default='')
    internal_slip_handling = Column('社内伝票扱い', SmallInteger, nullable=False, default=0)
    slip_type = Column('伝票種類', SmallInteger, nullable=False, default=0)
    property_number = Column('物件番号', Integer)
    welcia_property_content_code = Column('ウエルシア物件内容CD', Integer, nullable=False, default=0)
    welcia_property_content_name = Column('ウエルシア物件内容名', String(60), nullable=False, default='')
    welcia_lease_category = Column('ウエルシアリース区分', Integer, nullable=False, default=0)
    welcia_property_category_code = Column('ウエルシア物件区分CD', Integer, nullable=False, default=0)
    welcia_sales_floor_area = Column('ウエルシア売場面積', Float, nullable=False, default=0)
    reception_date = Column('受付日付', DateTime)
    completion_date = Column('完工日付', DateTime)
    ordering_staff_name = Column('発注担当者名', String(40), nullable=False, default='')
    work_content = Column('作業内容', String(40), nullable=False, default='')
    yk_supply_category = Column('YKサプライ区分', Integer, nullable=False, default=0)
    yk_property_category = Column('YK物件区分', Integer, nullable=False, default=0)
    yk_billing_category = Column('YK請求区分', Integer, nullable=False, default=0)
    cosmetics_manufacturer_category = Column('化粧品メーカー区分', Integer, nullable=False, default=0)
    sm_content_category = Column('SM内容区分', Integer, nullable=False, default=0)
    claim_category = Column('クレーム区分', Integer, nullable=False, default=0)
    sales_promotion_department_code = Column('営業推進部CD', SmallInteger, nullable=False, default=0)
    aggregation_code = Column('集計CD', String(10), nullable=False, default='')
    construction_staff_code = Column('工事担当CD', Integer, nullable=False, default=0)
    b_billing_jurisdiction_category = Column('B請求管轄区分', Integer, nullable=False, default=0)
    btob_number = Column('BtoB番号', Integer, nullable=False, default=0)
    industry_category = Column('業種区分', Integer, nullable=False, default=0)
    integrated_estimate_number = Column('統合見積番号', Integer, nullable=False, default=0)

    def __repr__(self):
        return f"<Estimate(estimate_number={self.estimate_number}, estimate_date={self.estimate_date})>"